binary_path = "./jenrik"

[invalid_arg]
args = ["-h"]
status = 1

[no_args]
args = []
status = 1

[init_only]
args = ["init"]
status = 1

[invalid_test_file]
args = ["toito"]
stderr = "toito : file not found\n"
status = 1

[invalid_test_file_but_toml]
args = ["toito.toml"]
stderr = "toito.toml : file not found\n"
status = 1

[overwrite_init_test_jenrik_toml]
args = ["init", "jenrik"]
stderr = "test_jenrik.toml already exists, can't init the file\n"
status = 1

[test_working_init]
args = ["init", "my_bin"]
status = 0
post = "rm -f test_my_bin.toml"

[empty_toml]
args = ["tests/empty.toml"]
status = 1
stderr = "Could not find binary_path key in tests/empty.toml\n"

[invalid_binary_path]
args = ["tests/invalid_path.toml"]
status = 1
stderr = "./toitoi : file not found\n"

[invalid_test_key]
args = ["tests/invalid_test_key.toml"]
status = 1
stderr = "invalid_test: Unknown key : toto\n"

[duplicate_stdout]
args = ["tests/duplicate_stdout.toml"]
status = 1
stderr = "invalid_test: Incompatible keys, 'stdout' and 'stdout_file'\n"

[duplicate_stderr]
args = ["tests/duplicate_stderr.toml"]
status = 1
stderr = "invalid_test: Incompatible keys, 'stderr' and 'stderr_file'\n"

[bad_test]
args = ["tests/invalid_test.toml"]
status = 1
stderr = "Invalid test : 'my_bad_test toto'\n"

[invalid_ouput_file]
args = ["tests/invalid_output_file.toml"]
status = 1
stderr = "tests/README.md : file not found\n"

[test_pipe_basic_stdout]
args = []
status = 1
pipe_stdout = "| grep \"USAGE\""
stdout = "USAGE : ./jenrik file.jrk | init path_to_binary\n"

[test_pipe_two_pipes_stdout]
args = []
status = 1
pipe_stdout = "| grep \"USAGE\" | cut -d ' ' -f1"
stdout = "USAGE\n"

[test_pipe_stderr]
args = ["tests/duplicate_stderr.toml"]
status = 1
pipe_stderr = "| cut -d ':' -f1"
stderr = "invalid_test\n"

[test_timeout_success]
args = []
status = 1
timeout= 0.1

[test_timeout_fail]
args = []
status = 1
timeout= 0
should_fail = true

[test_timeout_loop]
args = ["tests/infinite_loop.toml"]
status = 0
timeout = 0.5
should_fail = true

[test_status_should_fail]
args = []
status = 0
should_fail = true

[test_stdin]
args = ["tests/test_stdin.toml"]
status = 0

[test_env]
args = ["tests/echo_user_test.toml"]
status = 0

[test_bad_env_values]
args = ["tests/test_bad_types.toml"]
status = 1
